print ("please fill out the form ")
name = input("name: ")
age = input("age: ")
adress = input("adress: ")
email = input("email: ")
print ( "hello!" " \n please check if the folowing is correct:" "\n your name is: " + name + "\n you are " + age + " years old" "\n you live in: " + address + "\n we can contact you through: " + email )
